### ISSUE TITLE
github-api does not distinguish between user and organisation

### ISSUE THREAD

**Issue by luizkowalski** [kohsuke/github-api#260] opened 2016-03-15 21:56 UTC
if you for example, call the API giving an user instead an organization login, the API can't distinguish between them and will return an "empty" organization with some user data

**Comment by luizkowalski** [comment] 2016-05-10 10:06
following up

**Comment by kohsuke** [comment] 2016-06-04 03:28
Duplicate of #126

**Closed by kohsuke** 2016-06-04 03:28 UTC
